spring:
  profiles.active: ${MVC_ACTIVE_PROFILE:production}
  application:
    name: myforum
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    basename: messages
---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/myforum
    username: root
logging:
  file: logs/log_dev.txt
server:
  port: 8090
---
spring:
  profiles: production
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
    ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgres://qyvpckfmhnmbdr:44cffcf65dbd7800993bfac188b96ff9a709b37ead3959546c8b53186ce1236d@ec2-54-247-81-88.eu-west-1.compute.amazonaws.com:5432/d8uv6hi3n5firk
    username: qyvpckfmhnmbdr
    password: 44cffcf65dbd7800993bfac188b96ff9a709b37ead3959546c8b53186ce1236d
    driverClassName: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver