spring:
  profiles.active: production
  application:
    name: myforum
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    basename: messages
---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/myforum
    username: root
logging:
  file: logs/log_dev.txt
server:
  port: 8090
---
spring:
  profiles: production
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://eu-cdbr-west-02.cleardb.net/heroku_f9bafd14ded1286?reconnect=true
    username: b76bd918e77c2d
    password: 515c5fa0