spring:
  profiles.active: ${FORUM_ACTIVE_PROFILE:dev}
  application:
    name: myforum
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    basename: messages
---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/myforum
    username: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
  file: logs/log_dev.txt
server:
  port: 8090
---
spring:
  profiles: production
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
  datasource:
    url: ${FORUM_CONNECTION_URL}
    username: ${FORUM_DB_USER}
    password: ${FORUM_DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver